### ISSUE TITLE
.unpipe is not a function

### ISSUE THREAD

**Issue by danielkwinsor** [dominictarr/through#46]
Hi,

A Readable stream should have [unpipe](https://nodejs.org/api/stream.html#stream_readable_unpipe_destination)
However, I get the error that .unpipe is not a function, even though .pipe does actually work.
So it seems like this is 'readable', not 'Readable'.
Any chance of supporting this and any other Readable API function?

version 2.6.3

**Comment by dominictarr** [comment]
That's because this is a _classic stream_ (see my article on the [history of streams](http://dominictarr.com/post/145135293917/history-of-streams))

if you need streams2 features, there is https://www.npmjs.com/package/through2
personally, I've switched entirely to https://github.com/pull-stream which are massively simpler than node streams.

**Comment by MutableLoss** [comment]
This feels like information that could be added to the Introduction in the Documentation, no? 

Either way, I'm glad I ran across this while looking for an answer to an issue (which this explains).

**Comment by dominictarr** [comment]
I would be happy to merge PR for documentation on this
